# Generated by Django 5.0.1 on 2024-04-14 19:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteid', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('academic_level', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('sport_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='Employee', max_length=100)),
                ('address', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Salary', 'Salary'), ('Hourly', 'Hourly')], default='Salary', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(max_length=100)),
                ('ranking', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('established_date', models.DateField(default=django.utils.timezone.now)),
                ('incomeS1', models.IntegerField(default=0)),
                ('costS1', models.IntegerField(default=0)),
                ('incomeS2', models.IntegerField(default=0)),
                ('costS2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarshipid', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('donor', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('athleteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletic_department.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('rankingid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ranking', models.IntegerField()),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='athletic_department.team')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeid', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletic_department.team')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(default='', max_length=100)),
                ('venue', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('incomeS1', models.IntegerField(default=0)),
                ('costS1', models.IntegerField(default=0)),
                ('incomeS2', models.IntegerField(default=0)),
                ('costS2', models.IntegerField(default=0)),
                ('opponent', models.CharField(default='', max_length=100)),
                ('teamid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='athletic_department.team')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentid', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('incomeS1', models.IntegerField(default=0)),
                ('costS1', models.IntegerField(default=0)),
                ('incomeS2', models.IntegerField(default=0)),
                ('costS2', models.IntegerField(default=0)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='athletic_department.team')),
            ],
        ),
    ]
