# Generated by Django 5.0.1 on 2024-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_department', '0002_alter_event_date_alter_event_opponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
