# Generated by Django 5.0.1 on 2024-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_department', '0003_athlete_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='costS1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='costS2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='incomeS1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='incomeS2',
            field=models.IntegerField(default=0),
        ),
    ]
