# Generated by Django 5.0.1 on 2024-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletic_department', '0004_team_costs1_team_costs2_team_incomes1_team_incomes2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teamid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
